// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `dsf_ice_inf.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __dsf_ice_inf_h__
#define __dsf_ice_inf_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/BuiltinSequences.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace DSF
{

class DsfIceInf;
class DsfIceInfPrx;

}

namespace DSF
{

struct TagValue
{
    ::std::string name;
    ::std::string type;
    int errCode;
    ::Ice::ByteSeq value;

    /**
     * Obtains a tuple containing all of the exception's data members.
     * @return The data members in a tuple.
     */

    std::tuple<const ::std::string&, const ::std::string&, const int&, const ::Ice::ByteSeq&> ice_tuple() const
    {
        return std::tie(name, type, errCode, value);
    }
};

using TagValueSeq = ::std::vector<TagValue>;

struct ReadResult
{
    int errCode;
    TagValueSeq values;

    /**
     * Obtains a tuple containing all of the exception's data members.
     * @return The data members in a tuple.
     */

    std::tuple<const int&, const TagValueSeq&> ice_tuple() const
    {
        return std::tie(errCode, values);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace DSF
{

class DsfIceInf : public virtual ::Ice::Object
{
public:

    using ProxyType = DsfIceInfPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual bool queryRmStatus(const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_queryRmStatus(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual ReadResult drRead(::Ice::StringSeq names, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_drRead(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual int drSave(TagValueSeq values, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_drSave(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace DSF
{

class DsfIceInfPrx : public virtual ::Ice::Proxy<DsfIceInfPrx, ::Ice::ObjectPrx>
{
public:

    bool queryRmStatus(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<bool>(true, this, &DsfIceInfPrx::_iceI_queryRmStatus, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto queryRmStatusAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<bool>>().get_future())
    {
        return _makePromiseOutgoing<bool, P>(false, this, &DsfIceInfPrx::_iceI_queryRmStatus, context);
    }

    ::std::function<void()>
    queryRmStatusAsync(::std::function<void(bool)> response,
                       ::std::function<void(::std::exception_ptr)> ex = nullptr,
                       ::std::function<void(bool)> sent = nullptr,
                       const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<bool>(response, ex, sent, this, &DsfIceInfPrx::_iceI_queryRmStatus, context);
    }

    /// \cond INTERNAL
    void _iceI_queryRmStatus(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>&, const ::Ice::Context&);
    /// \endcond

    ReadResult drRead(const ::Ice::StringSeq& names, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<ReadResult>(true, this, &DsfIceInfPrx::_iceI_drRead, names, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto drReadAsync(const ::Ice::StringSeq& names, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<ReadResult>>().get_future())
    {
        return _makePromiseOutgoing<ReadResult, P>(false, this, &DsfIceInfPrx::_iceI_drRead, names, context);
    }

    ::std::function<void()>
    drReadAsync(const ::Ice::StringSeq& names,
                ::std::function<void(ReadResult)> response,
                ::std::function<void(::std::exception_ptr)> ex = nullptr,
                ::std::function<void(bool)> sent = nullptr,
                const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<ReadResult>(response, ex, sent, this, &DsfIceInfPrx::_iceI_drRead, names, context);
    }

    /// \cond INTERNAL
    void _iceI_drRead(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<ReadResult>>&, const ::Ice::StringSeq&, const ::Ice::Context&);
    /// \endcond

    int drSave(const TagValueSeq& values, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<int>(true, this, &DsfIceInfPrx::_iceI_drSave, values, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto drSaveAsync(const TagValueSeq& values, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<int>>().get_future())
    {
        return _makePromiseOutgoing<int, P>(false, this, &DsfIceInfPrx::_iceI_drSave, values, context);
    }

    ::std::function<void()>
    drSaveAsync(const TagValueSeq& values,
                ::std::function<void(int)> response,
                ::std::function<void(::std::exception_ptr)> ex = nullptr,
                ::std::function<void(bool)> sent = nullptr,
                const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<int>(response, ex, sent, this, &DsfIceInfPrx::_iceI_drSave, values, context);
    }

    /// \cond INTERNAL
    void _iceI_drSave(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, const TagValueSeq&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    DsfIceInfPrx() = default;
    friend ::std::shared_ptr<DsfIceInfPrx> IceInternal::createProxy<DsfIceInfPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits<::DSF::TagValue>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 7;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::DSF::TagValue, S>
{
    static void read(S* istr, ::DSF::TagValue& v)
    {
        istr->readAll(v.name, v.type, v.errCode, v.value);
    }
};

template<>
struct StreamableTraits<::DSF::ReadResult>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 5;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::DSF::ReadResult, S>
{
    static void read(S* istr, ::DSF::ReadResult& v)
    {
        istr->readAll(v.errCode, v.values);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace DSF
{

using DsfIceInfPtr = ::std::shared_ptr<DsfIceInf>;
using DsfIceInfPrxPtr = ::std::shared_ptr<DsfIceInfPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace DSF
{

class DsfIceInf;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< ::IceProxy::DSF::DsfIceInf>&);
::IceProxy::Ice::Object* upCast(::IceProxy::DSF::DsfIceInf*);
/// \endcond

}

}

namespace DSF
{

class DsfIceInf;
/// \cond INTERNAL
::Ice::Object* upCast(DsfIceInf*);
/// \endcond
typedef ::IceInternal::Handle< DsfIceInf> DsfIceInfPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::DSF::DsfIceInf> DsfIceInfPrx;
typedef DsfIceInfPrx DsfIceInfPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(DsfIceInfPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace DSF
{

struct TagValue
{
    ::std::string name;
    ::std::string type;
    ::Ice::Int errCode;
    ::Ice::ByteSeq value;
};

typedef ::std::vector<DSF::TagValue> TagValueSeq;

struct ReadResult
{
    ::Ice::Int errCode;
    TagValueSeq values;
};

}

namespace DSF
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::DSF::DsfIceInf::begin_queryRmStatus.
 * Create a wrapper instance by calling ::DSF::newCallback_DsfIceInf_queryRmStatus.
 */
class Callback_DsfIceInf_queryRmStatus_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_DsfIceInf_queryRmStatus_Base> Callback_DsfIceInf_queryRmStatusPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::DSF::DsfIceInf::begin_drRead.
 * Create a wrapper instance by calling ::DSF::newCallback_DsfIceInf_drRead.
 */
class Callback_DsfIceInf_drRead_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_DsfIceInf_drRead_Base> Callback_DsfIceInf_drReadPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::DSF::DsfIceInf::begin_drSave.
 * Create a wrapper instance by calling ::DSF::newCallback_DsfIceInf_drSave.
 */
class Callback_DsfIceInf_drSave_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_DsfIceInf_drSave_Base> Callback_DsfIceInf_drSavePtr;

}

namespace IceProxy
{

namespace DSF
{

class DsfIceInf : public virtual ::Ice::Proxy<DsfIceInf, ::IceProxy::Ice::Object>
{
public:

    bool queryRmStatus(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_queryRmStatus(_iceI_begin_queryRmStatus(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_queryRmStatus(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_queryRmStatus(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_queryRmStatus(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_queryRmStatus(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_queryRmStatus(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_queryRmStatus(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_queryRmStatus(const ::DSF::Callback_DsfIceInf_queryRmStatusPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_queryRmStatus(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_queryRmStatus(const ::Ice::Context& context, const ::DSF::Callback_DsfIceInf_queryRmStatusPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_queryRmStatus(context, cb, cookie);
    }

    bool end_queryRmStatus(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_queryRmStatus(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::DSF::ReadResult drRead(const ::Ice::StringSeq& names, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_drRead(_iceI_begin_drRead(names, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_drRead(const ::Ice::StringSeq& names, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_drRead(names, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_drRead(const ::Ice::StringSeq& names, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_drRead(names, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_drRead(const ::Ice::StringSeq& names, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_drRead(names, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_drRead(const ::Ice::StringSeq& names, const ::DSF::Callback_DsfIceInf_drReadPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_drRead(names, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_drRead(const ::Ice::StringSeq& names, const ::Ice::Context& context, const ::DSF::Callback_DsfIceInf_drReadPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_drRead(names, context, cb, cookie);
    }

    ::DSF::ReadResult end_drRead(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_drRead(const ::Ice::StringSeq&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::Ice::Int drSave(const ::DSF::TagValueSeq& values, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_drSave(_iceI_begin_drSave(values, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_drSave(const ::DSF::TagValueSeq& values, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_drSave(values, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_drSave(const ::DSF::TagValueSeq& values, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_drSave(values, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_drSave(const ::DSF::TagValueSeq& values, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_drSave(values, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_drSave(const ::DSF::TagValueSeq& values, const ::DSF::Callback_DsfIceInf_drSavePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_drSave(values, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_drSave(const ::DSF::TagValueSeq& values, const ::Ice::Context& context, const ::DSF::Callback_DsfIceInf_drSavePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_drSave(values, context, cb, cookie);
    }

    ::Ice::Int end_drSave(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_drSave(const ::DSF::TagValueSeq&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace DSF
{

class DsfIceInf : public virtual ::Ice::Object
{
public:

    typedef DsfIceInfPrx ProxyType;
    typedef DsfIceInfPtr PointerType;

    virtual ~DsfIceInf();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual bool queryRmStatus(const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_queryRmStatus(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual ReadResult drRead(const ::Ice::StringSeq& names, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_drRead(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual ::Ice::Int drSave(const TagValueSeq& values, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_drSave(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const DsfIceInf& lhs, const DsfIceInf& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const DsfIceInf& lhs, const DsfIceInf& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::DSF::TagValue>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 7;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::DSF::TagValue, S>
{
    static void write(S* ostr, const ::DSF::TagValue& v)
    {
        ostr->write(v.name);
        ostr->write(v.type);
        ostr->write(v.errCode);
        ostr->write(v.value);
    }
};

template<typename S>
struct StreamReader< ::DSF::TagValue, S>
{
    static void read(S* istr, ::DSF::TagValue& v)
    {
        istr->read(v.name);
        istr->read(v.type);
        istr->read(v.errCode);
        istr->read(v.value);
    }
};

template<>
struct StreamableTraits< ::DSF::ReadResult>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 5;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::DSF::ReadResult, S>
{
    static void write(S* ostr, const ::DSF::ReadResult& v)
    {
        ostr->write(v.errCode);
        ostr->write(v.values);
    }
};

template<typename S>
struct StreamReader< ::DSF::ReadResult, S>
{
    static void read(S* istr, ::DSF::ReadResult& v)
    {
        istr->read(v.errCode);
        istr->read(v.values);
    }
};

}
/// \endcond

namespace DSF
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::DSF::DsfIceInf::begin_queryRmStatus.
 * Create a wrapper instance by calling ::DSF::newCallback_DsfIceInf_queryRmStatus.
 */
template<class T>
class CallbackNC_DsfIceInf_queryRmStatus : public Callback_DsfIceInf_queryRmStatus_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_DsfIceInf_queryRmStatus(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        DsfIceInfPrx proxy = DsfIceInfPrx::uncheckedCast(result->getProxy());
        bool ret;
        try
        {
            ret = proxy->end_queryRmStatus(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DSF::DsfIceInf::begin_queryRmStatus.
 */
template<class T> Callback_DsfIceInf_queryRmStatusPtr
newCallback_DsfIceInf_queryRmStatus(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DsfIceInf_queryRmStatus<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DSF::DsfIceInf::begin_queryRmStatus.
 */
template<class T> Callback_DsfIceInf_queryRmStatusPtr
newCallback_DsfIceInf_queryRmStatus(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DsfIceInf_queryRmStatus<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::DSF::DsfIceInf::begin_queryRmStatus.
 * Create a wrapper instance by calling ::DSF::newCallback_DsfIceInf_queryRmStatus.
 */
template<class T, typename CT>
class Callback_DsfIceInf_queryRmStatus : public Callback_DsfIceInf_queryRmStatus_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_DsfIceInf_queryRmStatus(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        DsfIceInfPrx proxy = DsfIceInfPrx::uncheckedCast(result->getProxy());
        bool ret;
        try
        {
            ret = proxy->end_queryRmStatus(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DSF::DsfIceInf::begin_queryRmStatus.
 */
template<class T, typename CT> Callback_DsfIceInf_queryRmStatusPtr
newCallback_DsfIceInf_queryRmStatus(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DsfIceInf_queryRmStatus<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DSF::DsfIceInf::begin_queryRmStatus.
 */
template<class T, typename CT> Callback_DsfIceInf_queryRmStatusPtr
newCallback_DsfIceInf_queryRmStatus(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DsfIceInf_queryRmStatus<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::DSF::DsfIceInf::begin_drRead.
 * Create a wrapper instance by calling ::DSF::newCallback_DsfIceInf_drRead.
 */
template<class T>
class CallbackNC_DsfIceInf_drRead : public Callback_DsfIceInf_drRead_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ReadResult&);

    CallbackNC_DsfIceInf_drRead(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        DsfIceInfPrx proxy = DsfIceInfPrx::uncheckedCast(result->getProxy());
        ReadResult ret;
        try
        {
            ret = proxy->end_drRead(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DSF::DsfIceInf::begin_drRead.
 */
template<class T> Callback_DsfIceInf_drReadPtr
newCallback_DsfIceInf_drRead(const IceUtil::Handle<T>& instance, void (T::*cb)(const ReadResult&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DsfIceInf_drRead<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DSF::DsfIceInf::begin_drRead.
 */
template<class T> Callback_DsfIceInf_drReadPtr
newCallback_DsfIceInf_drRead(T* instance, void (T::*cb)(const ReadResult&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DsfIceInf_drRead<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::DSF::DsfIceInf::begin_drRead.
 * Create a wrapper instance by calling ::DSF::newCallback_DsfIceInf_drRead.
 */
template<class T, typename CT>
class Callback_DsfIceInf_drRead : public Callback_DsfIceInf_drRead_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ReadResult&, const CT&);

    Callback_DsfIceInf_drRead(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        DsfIceInfPrx proxy = DsfIceInfPrx::uncheckedCast(result->getProxy());
        ReadResult ret;
        try
        {
            ret = proxy->end_drRead(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DSF::DsfIceInf::begin_drRead.
 */
template<class T, typename CT> Callback_DsfIceInf_drReadPtr
newCallback_DsfIceInf_drRead(const IceUtil::Handle<T>& instance, void (T::*cb)(const ReadResult&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DsfIceInf_drRead<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DSF::DsfIceInf::begin_drRead.
 */
template<class T, typename CT> Callback_DsfIceInf_drReadPtr
newCallback_DsfIceInf_drRead(T* instance, void (T::*cb)(const ReadResult&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DsfIceInf_drRead<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::DSF::DsfIceInf::begin_drSave.
 * Create a wrapper instance by calling ::DSF::newCallback_DsfIceInf_drSave.
 */
template<class T>
class CallbackNC_DsfIceInf_drSave : public Callback_DsfIceInf_drSave_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_DsfIceInf_drSave(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        DsfIceInfPrx proxy = DsfIceInfPrx::uncheckedCast(result->getProxy());
        ::Ice::Int ret;
        try
        {
            ret = proxy->end_drSave(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DSF::DsfIceInf::begin_drSave.
 */
template<class T> Callback_DsfIceInf_drSavePtr
newCallback_DsfIceInf_drSave(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DsfIceInf_drSave<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DSF::DsfIceInf::begin_drSave.
 */
template<class T> Callback_DsfIceInf_drSavePtr
newCallback_DsfIceInf_drSave(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DsfIceInf_drSave<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::DSF::DsfIceInf::begin_drSave.
 * Create a wrapper instance by calling ::DSF::newCallback_DsfIceInf_drSave.
 */
template<class T, typename CT>
class Callback_DsfIceInf_drSave : public Callback_DsfIceInf_drSave_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_DsfIceInf_drSave(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        DsfIceInfPrx proxy = DsfIceInfPrx::uncheckedCast(result->getProxy());
        ::Ice::Int ret;
        try
        {
            ret = proxy->end_drSave(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DSF::DsfIceInf::begin_drSave.
 */
template<class T, typename CT> Callback_DsfIceInf_drSavePtr
newCallback_DsfIceInf_drSave(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DsfIceInf_drSave<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DSF::DsfIceInf::begin_drSave.
 */
template<class T, typename CT> Callback_DsfIceInf_drSavePtr
newCallback_DsfIceInf_drSave(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DsfIceInf_drSave<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
