 -- 驱动信息表
CREATE TABLE T_DD_SM_DRIVER (
    DRIVER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '驱动唯一id',
    DRIVER_NAME VARCHAR(64) NOT NULL COMMENT '驱动名称',
    DRIVER_TYPE VARCHAR(64) NOT NULL COMMENT '驱动类型,\'item\'|\'block\'',
    DESP VARCHAR(255) COMMENT '驱动描述',
    PRIMARY KEY (DRIVER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='驱动信息表';
 
-- 通道表
CREATE TABLE T_DD_SM_CHANNEL (
    CHANNEL_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '通道唯一标识',
    CHANNEL_NAME VARCHAR(64) NOT NULL COMMENT '通道名称',
    CHANNEL_TYPE VARCHAR(32) NOT NULL COMMENT '通道类型',
    DRIVER_ID INT UNSIGNED NOT NULL COMMENT '所属驱动ID',
    CONF LONGTEXT NOT NULL COMMENT '通道配置',
    DESP VARCHAR(255) COMMENT '通道描述',
    STATUS TINYINT DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    PRIMARY KEY (CHANNEL_ID),
    KEY IDX_DRIVER_ID (DRIVER_ID),
    CONSTRAINT FK_CHANNEL_DRIVER FOREIGN KEY (DRIVER_ID) REFERENCES T_DD_SM_DRIVER (DRIVER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通道表';
 
-- 设备表
CREATE TABLE T_DD_SM_DEVICE (
    DEVICE_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '唯一标识，自增',
    DRIVER_ID INT UNSIGNED NOT NULL COMMENT '驱动ID',
    DEVICE_NAME VARCHAR(32) NOT NULL COMMENT '设备名称',
    DESP VARCHAR(256) COMMENT '设备描述',
    CONF LONGTEXT NOT NULL COMMENT '驱动配置xml',
    PRIMARY KEY (DEVICE_ID),
    KEY IDX_DRIVER_ID (DRIVER_ID),
    CONSTRAINT FK_DEVICE_DRIVER FOREIGN KEY (DRIVER_ID) REFERENCES T_DD_SM_DRIVER (DRIVER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='设备表';
 
-- 数据类型表
CREATE TABLE T_DD_SM_TYPE (
    TYPE_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '类型标识，自增',
    TYPE_NAME TEXT NOT NULL COMMENT '类型名称，例如INT、WORD；说明：数组为ARRAY,模型为UDT',
    LENGTH INT UNSIGNED COMMENT '默认长度',
    PRIMARY KEY (TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据类型表';
 
-- 模型分组结构
CREATE TABLE T_DD_SM_MDL_GRP (
    NODE_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '唯一标识，自增',
    NODE_NAME VARCHAR(256) NOT NULL COMMENT '节点名称',
    PARENT_ID INT UNSIGNED COMMENT '父节点ID',
    NODE_TYPE SMALLINT NOT NULL DEFAULT 0 COMMENT '0为目录，1为表格',
    NAMESPACE VARCHAR(64) COMMENT '命名空间',
    PRIMARY KEY (NODE_ID),
    KEY IDX_PARENT_ID (PARENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模型分组结构';
 
-- 模型表总览
CREATE TABLE T_DD_SM_MDL (
    MODEL_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '唯一标识，自增',
    NODE_ID INT UNSIGNED NOT NULL COMMENT '所属节点ID',
    MODEL_NAME VARCHAR(256) NOT NULL COMMENT '模型名称',
    NAMESPACE VARCHAR(64) NOT NULL COMMENT '命名空间',
    DESP VARCHAR(256) NOT NULL COMMENT '描述',
    ALIGH_LENGTH VARCHAR(16) NOT NULL DEFAULT '4' COMMENT '对齐长度，例如 \'1\'|\'2\'|\'4\'|\'8\'',
    PRIMARY KEY (MODEL_ID),
    CONSTRAINT FK_MDL_NODE FOREIGN KEY (NODE_ID) REFERENCES T_DD_SM_MDL_GRP (NODE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模型表总览';
 
-- 模型属性表
CREATE TABLE T_DD_SM_MDL_PROP (
    PROP_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '唯一标识，自增',
    MODEL_ID INT UNSIGNED NOT NULL COMMENT '所属模型的id',
    PROP_NAME VARCHAR(256) NOT NULL COMMENT '属性名称',
    TYPE_ID INT UNSIGNED NOT NULL COMMENT '属性类型ID',
    TYPE_EXTRA JSON COMMENT '类型的补充信息，例如 { array_info:ARRAY[0..2] OF STD.MODEL1 model_id:1 }',
    INIT_VALUE BLOB COMMENT '初始值',
    DESP VARCHAR(256) COMMENT '描述',
    CONTROL_ENABLE SMALLINT DEFAULT 1 COMMENT '启用可写',
    PRIMARY KEY (PROP_ID),
    KEY IDX_MODEL_ID (MODEL_ID),
    KEY IDX_TYPE_ID (TYPE_ID),
    CONSTRAINT FK_MDLPROP_MODEL FOREIGN KEY (MODEL_ID) REFERENCES T_DD_SM_MDL (MODEL_ID),
    CONSTRAINT FK_MDLPROP_TYPE FOREIGN KEY (TYPE_ID) REFERENCES T_DD_SM_TYPE (TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模型属性表';
 
-- 模型散点表
CREATE TABLE T_DD_SM_MDL_INFO (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '唯一标识，自增',
    PARENT_MODEL_ID INT UNSIGNED NOT NULL COMMENT '所属模型的id',
    PROP_NAME VARCHAR(256) NOT NULL COMMENT '属性名称（全称）',
    TYPE_ID INT UNSIGNED NOT NULL COMMENT '属性类型ID',
    INIT_VALUE BLOB COMMENT '默认值',
    ALIAS VARCHAR(64) COMMENT '别名',
    DESP VARCHAR(255) COMMENT '描述',
    CONTROL_ENABLE SMALLINT DEFAULT 1 COMMENT '启用可写',
    PRIMARY KEY (ID),
    KEY IDX_PARENT_MODEL_ID (PARENT_MODEL_ID),
    KEY IDX_TYPE_ID (TYPE_ID),
    CONSTRAINT FK_MDLINFO_MODEL FOREIGN KEY (PARENT_MODEL_ID) REFERENCES T_DD_SM_MDL (MODEL_ID),
    CONSTRAINT FK_MDLINFO_TYPE FOREIGN KEY (TYPE_ID) REFERENCES T_DD_SM_TYPE (TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模型散点表';
 
-- 变量分组结构
CREATE TABLE T_DD_SM_VAR_GRP (
    NODE_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '唯一标识，自增',
    NODE_NAME VARCHAR(256) NOT NULL COMMENT '节点名称',
    PARENT_ID INT UNSIGNED COMMENT '父节点ID',
    NODE_TYPE SMALLINT NOT NULL DEFAULT 0 COMMENT '0为目录，1为表格',
    NAMESPACE VARCHAR(64) COMMENT '命名空间',
    PRIMARY KEY (NODE_ID),
    KEY IDX_PARENT_ID (PARENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='变量分组结构';
 

 -- 变量表【变量】
CREATE TABLE T_DD_SM_VAR (
    TAG_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '唯一标识，自增，二进制首位为0',
    TAG_NAME VARCHAR(256) NOT NULL COMMENT '变量名称',
    NODE_ID INT UNSIGNED NOT NULL COMMENT '所属节点ID',
    NAMESPACE VARCHAR(64) NOT NULL COMMENT '命名空间',
    TYPE_ID INT UNSIGNED NOT NULL COMMENT '类型ID（基础类型）',
    TYPE_EXTRA JSON COMMENT '类型的补充信息，{ELE_TYPE,STR_LENGTH,MODEL_ID,RANGE}',
    IO_ADDR TEXT COMMENT '地址（结构体和数组），优先级大于属性表',
    SCAN_INTV INT COMMENT '扫描周期(结构体和数组），优先级大于属性表',
    DEVICE_ID INT UNSIGNED COMMENT '设备ID（结构体和数组），优先级大于属性表',
    PRIMARY KEY (TAG_ID),
    KEY IDX_DEVICE_ID (DEVICE_ID),
    KEY IDX_NAMESPACE (NAMESPACE),
    CONSTRAINT FK_VAR_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES T_DD_SM_DEVICE (DEVICE_ID),
    CONSTRAINT FK_VAR_NODE FOREIGN KEY (NODE_ID) REFERENCES T_DD_SM_VAR_GRP (NODE_ID),
    CONSTRAINT FK_VAR_TYPE FOREIGN KEY (TYPE_ID) REFERENCES T_DD_SM_TYPE (TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='变量表';
 
-- 变量基础
CREATE TABLE T_DD_SM_VAR_PROP (
    PROP_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '唯一标识，自增,二进制首位为1',
    TAG_ID INT UNSIGNED NOT NULL COMMENT '变量ID',
    PROP_NAME VARCHAR(64) NOT NULL COMMENT '属性名称(全量名称）,例如STD::Q.A[0]',
    TYPE_ID INT UNSIGNED NOT NULL COMMENT '类型ID（基础类型）',
    IO_ADDR TEXT COMMENT '地址',
    INIT_VALUE BLOB COMMENT '初始值',
    DESP VARCHAR(256) COMMENT '描述',
    CONTROL_ENABLE SMALLINT NOT NULL COMMENT '控制使能',
    SCAN_INTV INT COMMENT '扫描周期',
    DEVICE_ID INT UNSIGNED COMMENT '设备ID',
    BYTE_ORDER VARCHAR(32) COMMENT '字节序',
    EVT_CTRL_ENABLE SMALLINT COMMENT '事件控制使能',
    EVT_CTRL_PRIOR INT COMMENT '事件控制优先级',
    OVERRIDE_ENABLE INT COMMENT '是否启用超驰（rt）',
    OVERRIDE_VALUE BLOB COMMENT '超驰值(rt)',
    MODIFY_TIME DATETIME COMMENT '修改时间',
    EGU_ENABLE SMALLINT DEFAULT 0 COMMENT '是否启用量程转换(AI)',
    RAW_HIGH DOUBLE COMMENT '原始值上限(AI)',
    RAW_LOW DOUBLE COMMENT '原始值下限(AI)',
    EGU_HIGH DOUBLE COMMENT '工程值上限(AI)',
    EGU_LOW DOUBLE COMMENT '工程值下限(AI)',
    LIMIT_HIGH DOUBLE COMMENT '上限(AI)',
    LIMIT_LOW DOUBLE COMMENT '下限(AI)',
    ZP_ENABLE SMALLINT COMMENT '零点使能',
    ZP_CENT DOUBLE COMMENT '零点中心',
    ZP_THRES DOUBLE COMMENT '零点阈值',
    EGU_LBL VARCHAR(16) COMMENT '工程单元标签',
    EGU_OPEN VARCHAR(16) COMMENT '开工程单位（DI）',
    EGU_CLOSE VARCHAR(16) COMMENT '关工程单位（DI）',
    PRIMARY KEY (PROP_ID),
    KEY IDX_TAG_ID (TAG_ID),
    KEY IDX_TYPE_ID (TYPE_ID),
    KEY IDX_DEVICE_ID (DEVICE_ID),
    CONSTRAINT FK_VARPROP_TAG FOREIGN KEY (TAG_ID) REFERENCES T_DD_SM_VAR (TAG_ID),
    CONSTRAINT FK_VARPROP_TYPE FOREIGN KEY (TYPE_ID) REFERENCES T_DD_SM_TYPE (TYPE_ID),
    CONSTRAINT FK_VARPROP_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES T_DD_SM_DEVICE (DEVICE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='变量基础表';
 
-- 数据类型库插入（执行完上述建表后针对t_dd_sm_type表执行）
INSERT INTO T_DD_SM_TYPE (TYPE_ID, TYPE_NAME, LENGTH) VALUES
(1, 'BOOL', 1),
(2, 'BYTE', 1),
(3, 'WORD', 2),
(4, 'DWORD', 4),
(5, 'LWORD', 8),
(6, 'SINT', 1),
(7, 'USINT', 1),
(8, 'INT', 2),
(9, 'UINT', 2),
(10, 'DINT', 4),
(11, 'UDINT', 4),
(12, 'LINT', 8),
(13, 'ULINT', 8),
(14, 'REAL', 4),
(15, 'LREAL', 8),
(16, 'CHAR', 1),
(17, 'STRING', 80),
(18, 'TIME', 4),
(19, 'TOD', 4),
(20, 'DT', 4),
(21, 'DATE', 4),
(22, 'LTIME', 8),
(23, 'LTOD', 8),
(24, 'LDT', 8),
(25, 'LDATE', 8),
(26, 'ARRAY', NULL),
(27, 'UDT', NULL);

